version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    networks:
      - HR_net

  db:
    image: mysql:latest
    container_name: mysql-db1
    ports:
      - '3307:3306'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: HR_DB
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass1234
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - HR_net


  hrmanage:
      image: hrmanament
      container_name: hrmanament
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      restart: always

      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db1:3306?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: pass1234
      networks:
        - HR_net

networks:
  HR_net:

volumes:
  db_data:

